name: Telegram RSS Scraper

on:
  schedule:
    - cron: '7-59/15 * * * *'  # Every 15 minutes starting at 7 minutes past the hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape_and_generate_rss:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 deep-translator

      - name: Run Telegram scraper
        run: python air_alerts_telegram_rss_translate.py

      # Debugging step: List files in the directory to verify if the XML file was created
      - name: List files after running script
        run: ls -la

      - name: Move RSS Feed to docs
        run: |
          mkdir -p docs
          mv air_alerts_telegram_feed.xml docs/

      - name: Commit and push if there's a change
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/air_alerts_telegram_feed.xml
          git commit -m "Update RSS feed" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
